Site/Controllers/POSController.cs
using Database;
using Site.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Site.Controllers
{
    public class POSController : Controller
    {
        // GET: POS
        public ActionResult Index()
        {
            DatabaseController db = new DatabaseController();
            var items = db.GetItems();

            //POSViewModel posVM = new POSViewModel();
            List<POSViewModel> posVM = new List<POSViewModel>();

            foreach(var item in items)
            {
                posVM.Add(new POSViewModel()
                {
                    Item = item,
                    ID = item.ID,
                    Quantity = 0
                });
            }
            //foreach(var item in items)
            //{

            //    posVM.Items.Add(item);
            //    posVM.Quantitys.Add(0);
            //    posVM.Quantities.Add(item.ID, 0);
            //    //posVM.Add(temp);
            //}
            //posVM.Items = items;
             return View(posVM);
        }

        [HttpPost]
        public ActionResult Index(List<POSViewModel> posVM)
        {
            var values = posVM;
            values = values.Where(i => i.Quantity > 0).ToList();
            Dictionary<int, int> keyValuePairs = new Dictionary<int, int>();
            foreach(var value in values)
            {
                keyValuePairs.Add(value.ID, value.Quantity);
            }

            DatabaseController db = new DatabaseController();
            db.RemoveStock(keyValuePairs);

            return RedirectToAction("Index", "Inventory");
        }

    }
}

Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
        <div class="container">
            <div class="navbar-brand">
                @Html.ActionLink("Inventory System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>*@
            @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>*@

            
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a>@Html.ActionLink("Point of Sale", "Index", "POS")</a>
                    <a>&nbsp;&nbsp;&nbsp;&nbsp;</a>
                    <a>@Html.ActionLink("Inventory", "Index", "Inventory")</a>
                </li>
            </ul>
         

            @*<div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("POS", "Index", "POS")</li>
                        <li>@Html.ActionLink("Inventory", "Index", "Inventory")</li>
                    </ul>
                </div>*@
        </div>
    </div>

    <br />
    <br />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Inventory System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>